### ISSUE TITLE
feat: 활동 추천 기능 구현

### ISSUE THREAD

**Issue by nebulaBdj** [KUSITMS-30th-TEAM-C/frontend#11]
### 📝 Description

홈 화면에서 시간 조각 모으러 가기 버튼 클릭 시 활동 추천 프로세스가 구현된 페이지로 이동
해당 페이지에서 구현해야 할 기능 구현을 위한 이슈

---

### 📝 Todo

- [x] 자투리 시간 입력 기능
- [x] 활동 유형 선택 기능
- [x] 사용자가 모든 키워드를 선택할 수 있는 활동 추천 로직 구현
- [x] 온라인, 오프라인, 온라인+오프라인에 따라 선택할 수 있는 키워드 변경
- [x] 오프라인 선택 시 사용자 위치 입력
- [x] 추천 결과 표시 페이지 구현
- [x] 활동중, 활동 종료 페이지
- [x] 사용자가 웹을 나갔다 들어와도 활동 기록 기능 (다시 들어왔을때 시간 종료시 홈에서 경고창, 시간이 계속되는 경우 활동 페이지 보여주기)
