### ISSUE TITLE
fix: 추천, 로그인, 활동 페이지 QA 반영 (1차)

### ISSUE THREAD

**Issue by nebulaBdj** [KUSITMS-30th-TEAM-C/frontend#43]
### 📝 Description

- QA 반영 

---

### 📝 Todo

- [x] 새로운 추천 시작 시 이전 활동 선택사항 남아 있는 문제 해결
- [x] 추천 이후 그래픽 매칭
- [ ] 자동 종료 시 로직 수정
- [x] 추천 시 로딩 화면 수정
- [ ] 활동 중 텍스트 레이아웃
- [x] 빠른 시작 연결
- [x] 로그인 레이아웃
