### ISSUE TITLE
fix: QA 최종 반영

### ISSUE THREAD

**Issue by nebulaBdj** [KUSITMS-30th-TEAM-C/frontend#50]
### 📝 Description

- 자동 종료 후 home 왔을때 저장 시간 계산 오류 수정
- 추천 로딩 페이지 배경색 설정
- 지도 검색 모달 수정
- 외 자잘한 QA 반영

---

### 📝 Todo

- [ ] 자동 종료 후 home 왔을때 저장 시간 계산 오류 수정
- [ ] 추천 로딩 페이지 배경색 설정
- [ ] 지도 검색 모달 수정
- [ ] 외 자잘한 QA 반영
